version: '3.4'

services:
  webapi:
    image: webapi
    depends_on:
      - biosample-db
    ports:
      - 80:80
  biosample-db:
    image: postgres:latest
    container_name: BiosampleDatabase
    environment:
      - POSTGRES_DB=biosample
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      - biosample-db
volumes:
  db:
    driver: local