version: '3.4'

services:
  webapi:
    image: biosample-api
    depends_on:
      - biosample-db
    ports:
      - 80:80
  biosample-db:
    image: postgres:latest
    container_name: BiosampleDatabase
    environment:
      - POSTGRES_DB=biosample
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db:
    driver: local